api_platform:
    title: dramatoons
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_enabled: true
        pagination_items_per_page: 100