framework:
    cache:
        default_redis_provider: 'redis://redis:6379'
        
        pools:
            cache.redis_tag_aware:
                adapter: cache.adapter.redis
                provider: 'redis://redis:6379'
                tags: true