name: dramatoons_api_staging

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: prod
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    volumes:
      - uploads_staging_data:/var/www/html/public/upload
      - ./config/jwt:/var/www/html/config/jwt
    networks:
      - shared_database_staging_network

  nginx:
    ports:
      - "127.0.0.1:8082:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/html/public:ro
      - uploads_staging_data:/var/www/html/public/upload:ro

  redis:
    command: redis-server --save 60 1 --loglevel warning --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_staging_data:/data

volumes:
  redis_staging_data:
  uploads_staging_data:

networks:
  shared_database_staging_network:
    name: shared_database_staging_network
    external: true