services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    networks:
      - shared_database_network
      - api_internal_network

  nginx:
    image: nginx:1.31.3-alpine3.24
    restart: unless-stopped
    depends_on:
      - php
    networks:
      - api_internal_network
      - global_proxy_network

  redis:
    image: redis:8.10.0-alpine3.23
    restart: unless-stopped
    networks:
      - api_internal_network

networks:
  shared_database_network:
    external: true
  api_internal_network:
    name: shared_api_network
    external: true
  global_proxy_network:
    external: true