services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - api_internal_network

  nginx:
    image: nginx:1.31.3-alpine3.24
    restart: unless-stopped
    depends_on:
      - php
    networks:
      - api_internal_network
      - global_proxy_network

  redis:
    image: redis:8.10.0-alpine3.23
    restart: unless-stopped
    networks:
      - api_internal_network

  mariadb:
    image: mariadb:12.3.2-noble
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_MYSQL_LOCALHOST_USER: "1"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-buffer-pool-size=512M
      - --max-connections=100
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - api_internal_network

networks:
  api_internal_network:
  global_proxy_network:
    external: true