services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    networks:
      - shared_database_network
      - api_internal_network

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - php
    networks:
      - api_internal_network

  redis:
    image: redis:8.10.0-alpine3.23
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - api_internal_network

volumes:
  redis_data:

networks:
  shared_database_network:
    external: true
  api_internal_network:
    name: shared_api_network
    external: true
