name: dramatoons_api_prod

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: prod
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    volumes:
      - uploads_prod_data:/var/www/html/public/upload
      - ./config/jwt:/var/www/html/config/jwt
    user: "0:0"

  nginx:
    ports:
      - "127.0.0.1:8082:80"
    entrypoint: [ "/bin/sh", "-c", "mkdir -p /var/www/html/public/upload && exec /docker-entrypoint.sh nginx -g 'daemon off;'" ]
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - uploads_prod_data:/var/www/html/public/upload

  redis:
    command: redis-server --save 60 1 --loglevel warning --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_prod_data:/data

  mariadb:
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - bdd_prod_data:/var/lib/mysql

volumes:
  redis_prod_data:
  uploads_prod_data:
  bdd_prod_data: