# RATE LIMITING
# Définit une zone mémoire (api_limit de 10 Mo) pour limiter chaque IP ($binary_remote_addr) à 10 requêtes par seconde
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

server {
    listen 80;

    server_name api.dramatoons.ovh api-staging.dramatoons.ovh dramatoons.api.local;
    root /var/www/html/public;
    index index.php;
    server_tokens off;

    # Force le navigateur à interagir uniquement en HTTPS pendant 1 an
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Limite les informations d'URL transmises lors de redirections externes
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # ROUTING PRINCIPAL SYMFONY
    location / {
        # Cherche le fichier ou dossier demandé ($uri). S'il n'existe pas, redirige vers index.php avec ses arguments
        try_files $uri /index.php$is_args$args;

        # Applique la limitation de débit (autorise un pic temporaire de 20 requêtes sans délai)
        limit_req zone=api_limit burst=20 nodelay;
    }

    # OPTIMISATION DES ASSETS STATIQUES
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|otf|ttf|svg)$ {
        expires 6M; # 6 mois

        access_log off; # Désactive l'écriture dans les logs d'accès aux fichiers

        # En-tête HTTP forçant la mise en cache publique et immuable par le navigateur/CDN
        add_header Cache-Control "public, max-age=15552000, immutable";
    }

    # TRAITEMENT DU FRONT CONTROLLER SYMFONY (PHP-FPM)
    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;

        # Découpe l'URI pour alimenter les variables $fastcgi_script_name et $fastcgi_path_info
        fastcgi_split_path_info ^(.+\.php)(/.*)$;

        # Charge la liste des variables d'environnement standard FastCGI
        include fastcgi_params;

        # Transmet à PHP le chemin absolu du fichier à exécuter (résout les liens symboliques de déploiement)
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;

        # Transmet à PHP le chemin absolu du dossier racine sans lien symbolique
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        # Sécurité : Interdit l'accès direct à /index.php depuis l'extérieur (accessible uniquement en interne via try_files)
        internal;
    }

    # SÉCURITÉ
    # Bloque l'exécution directe de tout autre fichier .php présent dans le projet
    location ~ \.php$ {
        return 404;
    }

    # LOGS
    # Fichier d'enregistrement des erreurs d'exécution NGINX
    error_log /var/log/nginx/project_error.log;

    # Fichier d'enregistrement des accès et requêtes réussies
    access_log /var/log/nginx/project_access.log;
}